# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[11,)" #mandatory (26 is current forge version)
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your optionHandles at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "${modIssueTracker}" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "${modId}" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "${modVersion}" #mandatory
# A display name for the mod
displayName = "${modName}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="https://raw.githubusercontent.com/kurrycat2004/MpkMod/main/update.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "${modUrl}" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "mpkmod_logo.png" #optional
# A text field displayed in the mod UI
credits = "" #optional
# A text field displayed in the mod UI
authors = "${modAuthors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
${modDescription}
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.

#[[dependencies.mpkmod]] #optional
#modId="forge"
#mandatory=true
#versionRange="[11,)"
#ordering="NONE"
#side="BOTH"

#[[dependencies.mpkmod]]
#modId="minecraft"
#mandatory=true
#versionRange="[1.8.9,)"
#ordering="NONE"
#side="BOTH"